services:

  db:
    image: postgres:17.2
    container_name: rma-db
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: rma-portal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  migrate:
      image: migrate/migrate
      depends_on:
        - db
      volumes:
        - /Users/anvi/Personal/rma-portal/cmd/migrate/migrations:/migrations
      command:
        [ "-path", "/migrations", "-database",  "postgres://admin:adminpassword@db:5432/rma-portal?sslmode=disable", "up" ]

  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data:
