create table if not exists tickets (
	id bigserial primary key,
	status integer not null,
	categories integer [],
	issue text not null,
	model citext,
	serial_number citext,
	sender_name citext not null,
	sender_email citext not null,
	sender_phone citext not null,
	sender_street citext not null,
	sender_city citext not null,
	sender_zip citext not null,
	sender_country citext not null,
	billing_name citext not null,
	billing_email citext not null,
	billing_phone citext not null,
	billing_street citext not null,
	billing_city citext not null,
	billing_zip citext not null,
	billing_country citext not null,
	inserted timestamp(0) with time zone default now(),
	updated timestamp(0) with time zone default now()
)
